### PR TITLE
alert-added-successfully

### PR DESCRIPTION
**Pull request by RoshanDasan**
I implemented some alert in this code. If you create new todo list in the website it show a beutiful alert . so it can inform user that a new list is added .And also added an alert in delete list section. You have to give OK condition to delete. Other wise it would not delete.

### CODE REVIEW

**Comment by RoshanDasan** [comment]
I successfully added some alert in add list and delete list.

**Comment by yatharth1706** [comment]
Thanks @RoshanDasan  for this PR. I will look into it in the evening. Will let you know 😃

**Comment by RoshanDasan** [comment]
OK. Thank you for your comment.

**Comment by yatharth1706** [comment]
Hi there, thank you for your PR. I will merge it in the evening.

**Pull request closed without merging**
